#!/usr/bin/env bash
# =============================================================================
# 根据台账生成人员笔记本 WireGuard Client 配置（wg0.conf）
# =============================================================================
#
# Usage:
#   ./scripts/wireguard/render-laptop-conf.sh <peer_name> [output_file]
#
# 示例:
#   ./scripts/wireguard/render-laptop-conf.sh laptop-billmiao
#   ./scripts/wireguard/render-laptop-conf.sh laptop-zhengyaoyuan ~/wg0.conf
#
# 依赖: peer 已 generate-peer；私钥在 ansible/keys/wireguard/<peer>.private
# 台账: docs/assets/wireguard-clients.yaml
#
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/wireguard/lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

CLIENTS_LEDGER="${WG_REPO_ROOT}/docs/assets/wireguard-clients.yaml"
HUB_ENDPOINT="${WG_HUB_ENDPOINT:-121.43.49.58:51820}"
HUB_DNS="${WG_HUB_DNS:-10.200.0.1}"
KEEPALIVE="${WG_KEEPALIVE:-25}"

usage() {
  cat <<EOF
Usage: $(basename "$0") <peer_name> [output_file]

  peer_name    如 laptop-zhengyaoyuan、laptop-billmiao（见 wireguard-clients.yaml）
  output_file  默认 stdout

Examples:
  $(basename "$0") laptop-billmiao
  $(basename "$0") laptop-zhengyaoyuan ./wg0-zhengyaoyuan.conf
EOF
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

PEER_NAME="$1"
OUTPUT="${2:-}"

PRIV_FILE="${WG_KEYS_DIR}/${PEER_NAME}.private"
[[ -f "$PRIV_FILE" ]] || wg_die "missing private key: ${PRIV_FILE} (run: wg-keys.sh generate-peer ${PEER_NAME})"
[[ -f "$WG_HUB_PUBLIC" ]] || wg_die "missing hub public key: ${WG_HUB_PUBLIC}"

PRIVATE_KEY="$(tr -d '[:space:]' <"$PRIV_FILE")"
HUB_PUB="$(tr -d '[:space:]' <"$WG_HUB_PUBLIC")"

read -r WG_IP ALLOWED_IPS <<<"$(python3 - "$CLIENTS_LEDGER" "$PEER_NAME" <<'PY'
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("python3 PyYAML required (make setup)")

ledger = Path(sys.argv[1])
peer_name = sys.argv[2]
data = yaml.safe_load(ledger.read_text(encoding="utf-8"))
profiles = data.get("allowed_ips_profiles", {})
member = next((m for m in data.get("members", []) if m.get("peer_name") == peer_name), None)
if not member:
    raise SystemExit(f"peer not found in ledger: {peer_name}")
profile = profiles.get(member.get("allowed_ips_profile", ""), {})
allowed = profile.get("value", "").replace(" ", "")
if not allowed:
    raise SystemExit(f"missing allowed_ips profile for {peer_name}")
print(member["wg_ip"], allowed)
PY
)"

CONF="$(cat <<EOF
# WireGuard Client — ${PEER_NAME}
# Generated by scripts/wireguard/render-laptop-conf.sh — do not commit private key

[Interface]
PrivateKey = ${PRIVATE_KEY}
Address = ${WG_IP}/32
DNS = ${HUB_DNS}

[Peer]
PublicKey = ${HUB_PUB}
Endpoint = ${HUB_ENDPOINT}
AllowedIPs = ${ALLOWED_IPS}
PersistentKeepalive = ${KEEPALIVE}
EOF
)"

if [[ -n "$OUTPUT" ]]; then
  printf '%s\n' "$CONF" >"$OUTPUT"
  chmod 600 "$OUTPUT"
  wg_log "wrote ${OUTPUT}"
else
  printf '%s\n' "$CONF"
fi
